[2018-10-13 22:57:33,242] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3058
[2018-10-13 22:58:04,643] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3058
[2018-10-14 17:19:50,513] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-14 17:28:38,097] [INFO] "GET /api/jingdianlist/1 HTTP/1.1" 200 3883
[2018-10-14 17:33:11,584] [INFO] "GET /api/jingqucount/1 HTTP/1.1" 200 72
[2018-10-14 17:33:54,285] [INFO] "GET /api/jingqucount/1 HTTP/1.1" 200 76
[2018-10-14 17:33:59,910] [INFO] "GET /api/jingqucount/2 HTTP/1.1" 200 77
[2018-10-14 17:34:21,414] [INFO] "GET /api/jingqucount/18 HTTP/1.1" 200 75
[2018-10-14 17:34:29,214] [INFO] "GET /api/jingqucount/17 HTTP/1.1" 200 76
[2018-10-14 17:34:35,536] [INFO] "GET /api/jingqucount/11 HTTP/1.1" 200 76
[2018-10-14 18:19:55,587] [ERROR] Internal Server Error: /api/jingqudetail/1
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 60, in get
    return get_jingqu_detail(request,id);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 19, in get_jingqu_detail
    this_year_comments = comment.objects(data_region__contains = search_key,comment_time__contains = str(datetime.datetime().year));
TypeError: Required argument 'year' (pos 1) not found
[2018-10-14 18:19:56,457] [ERROR] "GET /api/jingqudetail/1 HTTP/1.1" 500 96017
[2018-10-14 18:23:19,354] [ERROR] Internal Server Error: /api/jingqudetail/1
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 60, in get
    return get_jingqu_detail(request,id);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 44, in get_jingqu_detail
    res['thisMonthCommentNumber'] = this_year_month_comments.average('comment_score').count();
AttributeError: 'float' object has no attribute 'count'
[2018-10-14 18:23:37,456] [ERROR] "GET /api/jingqudetail/1 HTTP/1.1" 500 100176
[2018-10-14 18:24:12,886] [INFO] "GET /api/jingqudetail/1 HTTP/1.1" 200 236
[2018-10-14 18:27:43,292] [INFO] "GET /api/jingqudetail/2 HTTP/1.1" 200 237
[2018-10-14 20:17:15,698] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:18:02,709] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:18:04,641] [INFO] "OPTIONS /api/getAllTour HTTP/1.1" 200 0
[2018-10-14 20:18:04,705] [WARNING] Not Found: /api/getAllTour
[2018-10-14 20:18:04,710] [WARNING] "POST /api/getAllTour HTTP/1.1" 404 2882
[2018-10-14 20:20:29,291] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:20:43,092] [INFO] "OPTIONS /api/jingqulist HTTP/1.1" 200 0
[2018-10-14 20:20:43,155] [WARNING] "POST /api/jingqulist HTTP/1.1" 405 41
[2018-10-14 20:21:01,434] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:21:23,469] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
